language: node_js

node_js:
  - 6

cache:
  directories:
  - node_modules

script:
  - npm run build
  - npm test

env:
  global:
    - secure: "YdO58MU82DCoK+974Fi4qU83oUUNUXCaDlEIm0ITnLzGf0T2EpY+vyplfIx3gzxLEWo5tqFNLScqAzpSCWpTrbIEnXfrL1ryIDjHcIL9DutXOguV7eFfOKFP5zaH1AJ4aBjADxR+sK8c2hQd3e9T2bo5f8nzOtYfans8pnQr0BBJx/5sv2fsTUyYuOoAORkXpUDXbQGjfMXIbWi4lES1CYJb0vQoZLvJHVP1BPfJoDhwpchbJADEkG5mEOv3WZ4/So/hMgDNMWnepWijUOCW+ldEJlblyOW/Yx87EzizutqEBMfK6MGgrJIPjg01Jase6kMZA5y0jLGriBK/WEZsUhEi9INVZvr3TA4i8tUTQFtztn2lKQhnlq0iUaxeRhdee7tVTqpKDRAGXTT3mHVeviChmf/3CjI4KNlD0nNYhyz5XZrMZOZ788tIQ+cbtI9TTcXakOVuDXDdS7VP1ae3jJMvne5vcGp6hrDZmQ637+Sc/Kzbb89NWuDWe1E3bFORhUECmxWJ+TgccV8GCg/7sG9rMHUfCE4ZR0tFzRh5lDa6n1ajZ2ooJHTAnldndFjujzLHwsh7wXoLUvEypycvBg0rl5hwEELTQOKUlbjsbRKQx7K22OjonMSl+WNFdNhcoO8LlKJfLz0tXOmQVmsxFxyAtwftfNgSUsgB7oXaWMM="

addons:
  ssh_known_hosts: dev.seanjohnson.pro

before_deploy:
  - openssl aes-256-cbc -K $encrypted_cf0bead91dd2_key -iv $encrypted_cf0bead91dd2_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after ./build/* $SSHUSER@dev.seanjohnson.pro:debt-calculator
  on:
    branch: master
