language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
env:
  global:
  - secure: Mp1NvTczF2oUbfF4xbhRhZIEsOOYviAqnE+FDpaMd/861tfiOso7YJWLGliXyhCioqYrXjkxLUgTP7gXk6idyDv7awMsFeDsJdGqym4KDbbTj0GDoSuR0MHeXwohMKzXtaMuX4mIHoAyFwPV2FaRJo9RCPj8jiWkGGPnyc4gBOPp21xwf605zGxzSGW3HsF0sDDJjlEU3TVrB8VD4qVRBMU9oilY6IWUYTQG3EsCl2MUlxdVmH8H75sHXG5MColjWQr0FTVg/iv0v6amE8Bvvw9zG+6Kikw/iFvGcfV1ylM/92jKwQ96rIgy93PQTZB68gfqTAclgV3HXfk80lpwFhYkuFEaiEAX/txPaSg8/Y3NvNtzA9KTiMH1C0HBHlmUgH0uFbUrZHcGObPN4Do0cHGKYhjzGriKgV1DyHBxVWVebwBXdISdHib5/qPzLm0/SwtHjuxZU8nDpzQB3eej8/tkaZUWb1cjfzF5+yuwlE0a1xtIbJLC+w60sQzWsaK/jYQMmZKtLPa2pQ+ZdB3znqIsaL/t/7TwyabyJT4q3qDBOgVBiRFVMGJ9c51pK5no50l+qd7QzqvspT48dBmn6IhHPe1ghpRCzNSGxvAZCOT4N1WcKWVIF/2piHeL+O8/4fpP7vqNJXzphCea4S7/ULaBH+JV9fjvUhc+PKO9RdQ=
  - secure: CBhB9r6b04UCT4lrMDdTvG+hRaKqe8hehFAvHPfruypgA7/iG6QCtr6spcot7OTTBqssLeT0UfcxQKzs4phuVM/MlPCzHJlumXuBWEHiproe53yXvfsM+nbDUxLsd/FDL2uIzxIFPMJyB1oFM17SdX8aD0pX5zp7oS+uCgz6cpgyese9taRfUVreoJ9CBZNOYiNMe+IBxUkCQI2EC5ybWdtxMBKZ1haL8wdRh8VJYn2quPYb5GPGB1qqToaLNIXIoYyYY5PY7AaKXqhoaaJpjJO6IrqCKw0JNpvlP/dmWDJQ45w6PD08wxfqdwm4HJ3MDu2eApvzh9SQVht1yHVxUBVTcNu87ZvQ/1lKEGt+iFsePtKFxgOESJbd0SMVWxfuovPx84Rw4C5KRDV1zGf3RxDKp4y0IGWze5BxhPHvwu1lAv+26YbvKrV9v7REfPRfq9lGOQXWvHO6psLBN1XWqKle4MYxpUosFJ/rXaoCfGE5PbQc8B8Fb+yYNdGGitADn3a8aNqf6Mftds5R8oCSiflXX+WdYrjAAcG2yQr/FH/Ph0wBerg5z6wVKUG4v1DIe+0HZeWh+vckPvsp8r7hUzDxZlfJGzW54lJj/779X5mLulTMndL1w/GeWFOwCGk76MpJvfVsO/SXB1vK/EFaa3EuV3UeAtP5oqgJekFw9lc=

before_deploy:
  - openssl aes-256-cbc -K $encrypted_cf0bead91dd2_key -iv $encrypted_cf0bead91dd2_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build seandev@dev.seanjohnson.pro:debt-calculator
  on:
    branch: master